version: '3'

services:
  dockervpn:
    build: 
      context: ./src
    ports:
      - "1194:1194/udp"
    volumes:
      - ${PWD}/clients:/vpn/clients
      - ${PWD}/pki:/vpn/pki
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun

